spring.application.name=backend

spring.mvc.hiddenmethod.filter.enabled=true

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=${HIBERNATE_SHOW_SQL}
spring.jpa.properties.hibernate.format_sql=${HIBERNATE_FORMAT_SQL}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

logging.level.root=${LOGGING_LEVEL}

server.ssl.enabled=true
server.ssl.key-store-type=PKCS12
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password=${KEYSTORE_PASSWORD}
server.ssl.key-alias=amina
spring.cloud.aws.region.static=eu-north-1
spring.cloud.aws.s3.path-style-access-enabled=true