create table example
(
    id           integer generated by default as identity primary key,
    owner        varchar,
    text_message varchar
);

create table "user"
(
    id                    integer generated by default as identity primary key,
    username              varchar unique not null,
    password_hash         varchar        not null,
    public_key            varchar        not null,
    encrypted_private_key varchar        not null,
    created_at            timestamp      not null,
    updated_at            timestamp      not null
);

create table chat
(
    id         integer generated by default as identity primary key,
    name varchar not null,
    created_at timestamp not null,
    updated_at timestamp not null
);

create table user_chat
(
    user_id                 integer   not null references "user" (id) on delete cascade,
    chat_id                 integer   not null references chat (id) on delete cascade,
    encrypted_symmetric_key varchar   not null,
    created_at              timestamp not null,
    primary key (user_id, chat_id)
);

create table message
(
    id         integer generated by default as identity primary key,
    sender_id  integer references "user" (id) on delete cascade not null,
    chat_id    integer references chat (id) on delete cascade   not null,
    content    varchar                                          not null,
    created_at timestamp                                        not null,
    updated_at timestamp                                        not null
);
create index on message (chat_id, created_at asc);
create index on message (chat_id, created_at desc);

create table web_socket_token
(
    id      uuid primary key,
    user_id integer unique references "user" (id) on delete cascade not null
);

create table message_receiver
(
    message_id  integer references message (id) on delete cascade not null,
    chat_id integer references chat (id) on delete cascade not null,
    receiver_id integer references "user" (id) on delete cascade  not null,
    created_at  timestamp                                         not null,
    primary key (message_id, receiver_id)
);