create table example
(
    id           integer generated by default as identity primary key,
    owner        varchar,
    text_message varchar
);

create table "user"
(
    id                    integer generated by default as identity primary key,
    username              varchar unique not null,
    password_hash         varchar        not null,
    public_key            varchar        not null,
    encrypted_private_key varchar        not null,
    created_at            timestamp      not null,
    updated_at            timestamp      not null
);

create table chat
(
    id         integer generated by default as identity primary key,
    name varchar not null,
    created_at timestamp not null,
    updated_at timestamp not null
);

create table user_chat
(
    user_id    integer   not null references "user" (id) on delete cascade,
    chat_id    integer   not null references chat (id) on delete cascade,
    created_at timestamp not null default current_timestamp,
    primary key (user_id, chat_id)
);

create table message
(
    id         integer generated by default as identity primary key,
    sender_id  integer references "user" (id) on delete cascade not null,
    chat_id    integer references chat (id) on delete cascade   not null,
    content    varchar                                          not null,
    created_at timestamp                                        not null,
    updated_at timestamp                                        not null
);

create table web_socket_token
(
    id      uuid primary key,
    user_id integer unique references "user" (id) on delete cascade not null
);

create index idx_message_chat_id on message (chat_id);
create index idx_message_sender_id on message (sender_id);
create index idx_message_created_at on message (created_at);

create index idx_user_chat_user_id on user_chat (user_id);
create index idx_user_chat_chat_id on user_chat (chat_id);