### Зарегистрироваться
POST http://{{host}}:{{port}}/api/v1/auth/register
Content-Type: application/json

{
  "username": "username10",
  "passwordHash": "passsssssssssssssssssssssssssssssssssssssssssssssssssssswordHash",
  "publicKey": "publicKeypublicKeypublicKeypublicKeypublicKeypublicKeypublicKeypublicKey",
  "encryptedPrivateKey": "privateKeyprivateKeyprivateKeyprivateKeyprivateKeyprivateKeyprivateKey"
}

###
#{
#  "code": 201,
#  "message": "Created",
#  "data": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VybmFtZTEiLCJleHAiOjE3Njk2OTUwMTl9.DEgSidWavE-V--XSV99GckHhM7d05VV-VUMVxK7ki5U" // jwt
#}


### Войти
POST http://{{host}}:{{port}}/api/v1/auth/login
Content-Type: application/json

{
  "username": "username",
  "passwordHash": "passsssssssssssssssssssssssssssssssssssssssssssssssssssswordHash"
}

###
#{
#  "code": 200,
#  "message": "Success",
#  "data": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VybmFtZTEiLCJleHAiOjE3Njk2OTUwODZ9.XNXR0lqYoyB8F3MlP3fcohYMPX9y1sjpfhuTJ4wvrKA" // jwt
#}


### Опубликовать сообщение Example API
POST http://{{host}}:{{port}}/api/v1/example
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "owner": "test_owner",
  "textMessage": "test_textMessage"
}

###
#{
#  "code": 201,
#  "message": "Success",
#  "data": 5 // id нового добавленного сообщения Example API
#}

### Получить все сообщения Example API
GET http://{{host}}:{{port}}/api/v1/example
Authorization: Bearer {{jwt}}

###
#{
#  "code": 200,
#  "message": "Success",
#  "data": [
#    {
#      "id": 1,
#      "owner": "test_owner",
#      "textMessage": "test_textMessage"
#    },
#    ...,
#    {
#      "id": 5,
#      "owner": "test_owner",
#      "textMessage": "test_textMessage"
#    }
#  ] // список сообщений Example API
#}


### Получить сообщение по {{id}} Example API
GET http://{{host}}:{{port}}/api/v1/example/{{exampleId}}
Authorization: Bearer {{jwt}}

###
#{
#  "code": 200,
#  "message": "Success",
#  "data": {
#    "id": 2,
#    "owner": "test_owner",
#    "textMessage": "test_textMessage1"
#  } // сообщение Example API по {{id}}
#}

### Получить токен для подключения к вебсокету
POST http://{{host}}:{{port}}/api/v1/auth/ws-token
Authorization: Bearer {{jwt}}

###
#{
#  "code": 201,
#  "message": "Created",
#  "data": "9c623f1f-9a3c-4a7a-8d84-4d59f6a3dab2" // токен для подключения к http://{{host}}:{{port}}/ws?token=
#}

### Создать чат
POST http://{{host}}:{{port}}/api/v1/chat
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "chatName": "Hello chat",
  "usersDetails": [
    {
      "username": "Apkawa",
      "encryptedSymmetricKey": "some_key1"
    },
    {
      "username": "test_user2",
      "encryptedSymmetricKey": "some_key2"
    },
    {
      "username": "test_user3",
      "encryptedSymmetricKey": "some_key3"
    }
  ]
}

###
#{
#  "code": 201,
#  "message": "Created",
#  "data": 50,
#  "timestamp": "2026-01-07T08:38:35.275153945"
#}


### Получить информацию о чате по {{id}} // лучше использовать GET /api/v1/chat/{{chatId}}/message
GET http://{{host}}:{{port}}/api/v1/chat/{{chatId}}
Authorization: Bearer {{jwt}}

###
#{
#  "code": 200,
#  "message": "Success",
#  "data": {
#    "name": "Brothers",
#    "messages": [
#      {
#        "content": "test",
#        "sender": "Apkawa",
#        "createdAt": "2025-12-29T14:28:00.369663"
#      },
#      {
#        "content": "asdsfs",
#        "sender": "Apkawa",
#        "createdAt": "2025-12-29T14:25:51.391017"
#      }
#    ]
#  }
#}

### Получить список пользователей чата
GET http://{{host}}:{{port}}/api/v1/chat/{{chatId}}/users
Authorization: Bearer {{jwt}}

###
#{
#  "code": 200,
#  "message": "Success",
#  "data": [
#    {
#      "id": 16,
#      "username": "Tema"
#    },
#    {
#      "id": 15,
#      "username": "Apkawa"
#    }
#  ]
#}

### Получить список чатов пользователя с последними сообщениями и симметричными ключами в порядке даты последнего сообщения
GET http://{{host}}:{{port}}/api/v1/user/chats
Authorization: Bearer {{jwt}}

###
#{
#  "code": 200,
#  "message": "Success",
#  "data": [
#    {
#      "id": 48,
#      "name": "Family",
#      "encryptedPrivateKey": "",
#      "messageContent": "Hello",
#      "messageCreatedAt": "2026-01-06T15:45:38.394782",
#      "sortingDate": "2026-01-06T15:45:38.394782"
#    },
#    {
#      "id": 27,
#      "name": "Brothers3",
#      "encryptedPrivateKey": "",
#      "messageContent": "2",
#      "messageCreatedAt": "2026-01-06T14:01:40.000565",
#      "sortingDate": "2026-01-06T14:01:40.000565"
#    },
#    {
#      "id": 25,
#      "name": "Brothers",
#      "encryptedPrivateKey": "",
#      "messageContent": "4",
#      "messageCreatedAt": "2026-01-06T13:57:00.533211",
#      "sortingDate": "2026-01-06T13:57:00.533211"
#    },
#    {
#      "id": 47,
#      "name": "Hello chat",
#      "encryptedPrivateKey": "",
#      "messageContent": "asdf",
#      "messageCreatedAt": "2025-12-30T18:19:53.756401",
#      "sortingDate": "2025-12-30T18:19:53.756401"
#    },
#    {
#      "id": 29,
#      "name": "ApkawaLol",
#      "encryptedPrivateKey": "",
#      "messageContent": "asdf",
#      "messageCreatedAt": "2025-12-30T18:19:49.987245",
#      "sortingDate": "2025-12-30T18:19:49.987245"
#    }
#  ],
#  "timestamp": "2026-01-07T07:43:11.585945086"
#}

### Получить список всех сообщений чата в порядке даты сообщения
GET http://{{host}}:{{port}}/api/v1/chat/{{chatId}}/message
Authorization: Bearer {{jwt}}

###
#{
#  "code": 200,
#  "message": "Success",
#  "data": [
#    {
#      "sender": "Apkawa",
#      "content": "asdsfs",
#      "createdAt": "2025-12-29T14:25:51.391017" // самое раннее сообщение
#    },
#    {
#      "sender": "Apkawa",
#      "content": "test",
#      "createdAt": "2025-12-29T14:28:00.369663"
#    },
#    {
#      "sender": "Tema",
#      "content": "Привет всем",
#      "createdAt": "2025-12-29T14:38:04.023132"
#    },
#    {
#      "sender": "Apkawa",
#      "content": "Да да привет",
#      "createdAt": "2025-12-29T14:38:11.811434" // самое позднее сообщение
#    }
#  ]
#}


### Изменить сообщение по {{id}}
PATCH http://{{host}}:{{port}}/api/v1/chat/{{chatId}}/message/{{messageId}}
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "content": "New content"
}

###
#{ // пока что невозможно использовать, т.к. ты не знаешь id сообщений
#  "code": 200,
#  "message": "Success",
#  "data": "2025-12-29T14:38:11.811444"
#}

### Получить публичные ключи пользователей по username
GET http://{{host}}:{{port}}/api/v1/user/keys
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "usernames": [
    {
      "username": "test_user1"
    },
    {
      "username": "test_user2"
    },
    {
      "username": "test_user3"
    }
  ]
}

###
#{
#  "code": 200,
#  "message": "Success",
#  "data": [
#    {
#      "username": "test_user1",
#      "publicKey": "test_public_key"
#    },
#    {
#      "username": "test_user2",
#      "publicKey": "test_public_key"
#    },
#    {
#      "username": "test_user3",
#      "publicKey": "test_public_key"
#    }
#  ],
#  "timestamp": "2026-01-06T14:39:00.114769668"
#}


### Получить свой зашифрованный симметричный ключ по {{id}} чата
GET http://{{host}}:{{port}}/api/v1/chat/{{chatId}}/key
Authorization: Bearer {{jwt}}

#{
#  "code": 200,
#  "message": "Success",
#  "data": "", // зашифрованный симметричный ключ
#  "timestamp": "2026-01-07T08:35:39.087152699"
#}